# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Dynamic links.
github: 'https://github.com/Roastero/Openroast'
twitter: 'https://twitter.com/Roastero'
facebook: 'https://www.facebook.com/Roastero'
team: 'https://github.com/orgs/Roastero/people'
gitter: '#'
paypal: 'https://www.paypal.me/mspicer'
squarecash: 'https://cash.me/$MarkSpicer'
email: mds4680@rit.edu

# Build settings
markdown: kramdown
