# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Dynamic links.
github: 'https://github.com/roastero/roastero'
twitter: 'https://twitter.com/roastero'
facebook: 'https://www.facebook.com/roastero'
team: 'https://github.com/orgs/Roastero/people'
gitter: '#'
paypal: 'https://paypal.com'
bitcoin: 'https://coinbase.com'
email: admin@roastero.com

# Build settings
markdown: kramdown
